name: Deploy to Hot Iron Box
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Deploy to Hot Iron Box
        env:
          RTH_API_KEY: ${{secrets.RTH_API_KEY}}
        run: |
          f=$(mktemp)
          curl -fsSL https://host.retiehe.com/cli -o $f
          node $f --site silver422 --outdir .
